# Generated by Django 2.2.19 on 2021-05-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210502_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slug_gr',
            new_name='slug',
        ),
    ]
